# Generated by Django 6.0 on 2026-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_downloadtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=10),
        ),
    ]
