# Generated by Django 6.0 on 2026-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
