# Generated by Django 6.0 on 2026-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
