# Generated by Django 6.0 on 2026-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Avatar One'), (2, 'Avatar Two'), (3, 'Avatar Three'), (4, 'Avatar Four'), (5, 'Avatar Five'), (6, 'Avatar Six'), (7, 'Avatar Seven')], default=1),
        ),
    ]
