# Generated by Django 6.0 on 2026-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='EGL', max_length=50),
            preserve_default=False,
        ),
    ]
