# Generated by Django 6.0 on 2026-08-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='purchased_projects',
        ),
    ]
