# Generated by Django 6.0 on 2026-01-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, unique=True),
        ),
    ]
