# Generated by Django 6.0 on 2026-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_media',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.projectmedia'),
        ),
    ]
