# Generated by Django 6.0 on 2026-08-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_additional_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_media',
        ),
    ]
