# Generated by Django 6.0 on 2026-08-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_additional_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Hand-picked by the site owner for the Home page's 'Commander's Choice' tray. Toggle from the admin list."),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_media', to='projects.project'),
        ),
    ]
